# Generated by Django 5.2.7 on 2025-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='number_of_passengers',
            field=models.IntegerField(default=1),
        ),
    ]
