# Generated by Django 5.2.7 on 2025-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest_number_of_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=9876543210, max_length=15),
            preserve_default=False,
        ),
    ]
