# Generated by Django 5.2.7 on 2025-11-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_remove_user_google_id_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="current_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="current_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="dropoff_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="dropoff_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="pickup_latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="pickup_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
