# Generated by Django 5.2.7 on 2025-11-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='dropoff_longitude',
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='broadcast_radius',
            field=models.IntegerField(default=500),
        ),
    ]
