# Generated by Django 5.2.7 on 2025-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_remove_riderequest_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('no_drivers', 'No Drivers Available'), ('completed', 'Completed'), ('cancelled_user', 'Cancelled by User'), ('cancelled_driver', 'Cancelled by Driver')], default='pending', max_length=20),
        ),
    ]
