# Generated by Django 5.2.7 on 2025-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0008_rideoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="broadcast_radius",
            field=models.IntegerField(default=1000),
        ),
    ]
