# Generated by Django 5.2.7 on 2025-11-22 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0009_alter_riderequest_broadcast_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="last_location_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
